---
title: "biagio"
author: "Gabe"
date: "2023-02-07"
output: pdf_document
---

```{r setup, include=FALSE, cache = F}
knitr::opts_chunk$set(
  echo = FALSE,
  error = TRUE,
  warning= FALSE,
  message= FALSE)
# knitr::opts_chunk$set(include=FALSE, echo = FALSE, warning = FALSE)
```

# Graphical analysis of the definitions

```{r}
library(tidyverse)
library(tidytext)
library(yardstick)
library(janitor)
library(readxl)

raw_classified <- read_excel("data.xlsx", sheet = "Definition classification", range = "A1:U681", na = "") %>% 
  clean_names() %>% mutate(article_number = str_sub(string = id, start = 1, end = 6))
raw_classified %>% glimpse()
examined_articles <- raw_classified %>% distinct(article_number) %>% tally()
total_constructs <- raw_classified %>% nrow()
y_def <- raw_classified %>% count(str_to_lower(explicit_definition_y_n)) %>% 
  filter(`str_to_lower(explicit_definition_y_n)` == "y") %>% pull(n)

constructs <- c("Organizational capability", "IT capability",
                "IT-enabled capability", "Digital capability", "Excluded")

df_classified <-
  raw_classified %>% 
  mutate(discipline = case_when(field == "ACCOUNTING" ~ "Accounting",
                                field == "FINANCE" ~ "Finance",
                                field == "INFO MAN" ~ "Information Systems",
                                field == "MARKETING" ~ "Marketing",
                                str_detect(field, "OPERATION") ~ "Operations",
                                (field == "ENTREPRENEURSHIP" | field == "IB") ~ "Entrepreneurship and IB",
                                (field == "HR" | field == "ORGANISATION STUDIES" | field == "MANAGEMENT") ~ "Management",
                                (field == "STRATEGY" | field == "INNOVATION") ~ "Strategy and Innovation",
                                .default = NA)) %>% 
           mutate(construct = factor(type_of_construct, levels = constructs, ordered = TRUE), .keep = "all")



# df <- df_classified %>% filter(explicit_definition_y_n == "Y")
# glimpse(df)
#df <- rename(df, journal=source_title, , construct_type=construct)

```

### Construct name and definition preprocessing
```{r}
df_mutated <- df_classified %>% 
  mutate(construct_name_clean= str_replace_all(construct_name,  
                                               c("capabilities"= "capability","capabilites"= "capability",
                                                 "competencies"= "competence", "infrastructures"= "infrastructure",
                                                 "abilities"= "ability", "analytics"= "analytic", "IT" = "InformationTechnology", 
                                                 "IS"= "InformationSystems", "spannig" ="spanning")), 
         construct_def_clean= str_replace_all(construct_definition,  c("capabilities"= "capability","capabilites"= "capability", 
                                                                       "competencies"= "competence", 
                                                                       "infrastructures"= "infrastructure",
                                                                       "abilities"= "ability", "analytics"= "analytic", 
                                                                       "IT" = "InformationTechnology", "IS"= 
                                                                         "InformationSystems","spannig" ="spanning"))) %>%
  mutate(construct_name_clean= str_replace_all(construct_name_clean, "[:digit:]", ""), 
        construct_def_clean= str_replace_all(construct_def_clean, "[:digit:]", "")) %>% 
  mutate(construct_name_clean= str_to_lower(construct_name_clean, locale = "en"), 
         construct_def_clean=str_to_lower(construct_def_clean, locale = "en")) 
```

### Bigram analysis on construct name

```{r}
df_bigrams <- df_mutated %>%
  unnest_tokens(bigram, construct_name_clean, token = "ngrams", n = 2)%>%
  filter(!is.na(bigram))

#df_bigrams
df_bigrams %>%
  count(bigram, sort = TRUE)

bigrams_separated <- df_bigrams %>%
  separate(bigram, c("word1", "word2"), sep = " ")

bigrams_filtered <- bigrams_separated %>%
  filter(!word1 %in% stop_words$word) %>%
  filter(!word2 %in% stop_words$word)

# new bigram counts:
bigram_counts <- bigrams_filtered %>% 
  count(word1, word2, sort = TRUE)

bigrams_united <- bigrams_filtered %>%
  unite(bigram, word1, word2, sep = " ")

bigram_tf_idf <- bigrams_united %>%
  count(construct_name, bigram) %>%
  bind_tf_idf(bigram, construct_name, n) %>%
  arrange(desc(tf_idf))

library(igraph)

bigram_graph <- bigram_counts %>%
  filter(n > 1) %>%
  graph_from_data_frame()


library(ggraph)

set.seed(2020)

a <- grid::arrow(type = "closed", length = unit(.15, "inches"))

ggraph(bigram_graph, layout = "fr") +
  geom_edge_link(aes(edge_alpha = n), show.legend = FALSE,
                 arrow = a, end_cap = circle(.1, 'inches')) +
  geom_node_point(color = "lightblue", size = 2) +
  geom_node_text(aes(label = name), vjust = 0.5, hjust = 0.5, check_overlap = T) +
  theme_void()# repeat analysis on the definitions
```

In this section I perform a bigram analysis to explore the relationships between words in the construct name.
```{r results}

bigrams_united

bigram_counts

bigram_graph

ggraph(bigram_graph, layout = "fr") +
  geom_edge_link(aes(edge_alpha = n), show.legend = FALSE,
                 arrow = a, end_cap = circle(.1, 'inches')) +
  geom_node_point(color = "lightblue", size = 2) +
  geom_node_text(aes(label = name), vjust = 0.5, hjust = 0.5, check_overlap = T) +
  theme_void()# repeat analysis on the definitions
```

